name: Go

on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o bin/service

    - name: Test
      run: go test -v ./...